src/Entity/Message.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use App\Repository\MessageRepository;

/**
 * @ORM\Entity(repositoryClass=MessageRepository::class)
 */
class Message
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     */
    private $text;

    /**
     * @ORM\Column(type="datetime", nullable=true, options={"default": "CURRENT_TIMESTAMP"})
     */
    private $date_add;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="messages")
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity=Subject::class, inversedBy="messages")
     */
    private $subject;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getText(): ?string
    {
        return $this->text;
    }

    public function setText(string $text): self
    {
        $this->text = $text;

        return $this;
    }

    public function getDateAdd(): ?\DateTimeInterface
    {
        return $this->date_add;
    }

    public function setDateAdd(?\DateTimeInterface $date_add): self
    {
        $this->date_add = $date_add;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getSubject(): ?Subject
    {
        return $this->subject;
    }

    public function setSubject(?Subject $subject): self
    {
        $this->subject = $subject;

        return $this;
    }
}

src/Controller/ArticleController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Entity\Message;
use App\Entity\Subject;
use App\Form\MessageType;
use App\Form\SubjectType;
use App\Repository\UserRepository;
use App\Repository\MessageRepository;
use App\Repository\SubjectRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;


/**
* @Route("/articles")
*/
class ArticleController extends AbstractController
{
    /**
     * @Route("/", name="articles_index")
     */
    public function index(SubjectRepository $subjects)
    {
        return $this->render('article/index.html.twig', [
            'subjects' => $subjects->getAll(),
        ]);
    }



/**
 * @Route("/article/add", name="add_subject")
 *  @IsGranted("ROLE_USER")
 */
public function add_Subject(Subject $subject = null, Request $request, UserRepository $user)
{

    if(!$subject){
        $subject = new Subject();
    }

    $user = $this->getUser();
    
    $subject->setUser($user);
    $subject->setBlock(0);

    $form = $this->createForm(SubjectType::class, $subject);
    $form->handleRequest($request);

    if ($form->isSubmitted() && $form->isValid()) {
        $entityManager = $this->getDoctrine()->getManager();
      
        $entityManager->persist($subject);
        $entityManager->flush();

        $this->addFlash('message', 'Article ajouté avec succès');
        return $this->redirectToRoute('articles_index');
    }
    
    return $this->render('article/add_subject.html.twig', [
        'subjectForm' => $form->createView(),
    ]);
}


   
    /**
     * @Route("/article/{id}", name="article_show", methods={"GET","POST"})
     *  @IsGranted("ROLE_USER")
     */

    public function show(Subject $subject, MessageRepository $messages, Request $request, UserRepository $user, $id): Response {

    $message = new Message();

    $user = $this->getUser();

    $em = $this->getDoctrine()->getManager();
    $subjectRepo = $em->getRepository(Subject::class);

    $idSubject= $subjectRepo->find($id);

    $message->setUser($user);
    $message->setSubject($idSubject);
    $message->setDateAdd(new \DateTime('now'));

    $form = $this->createForm(MessageType::class, $message);
    $form->handleRequest($request);

    if ($form->isSubmitted() && $form->isValid()) {
        $entityManager = $this->getDoctrine()->getManager();
      
        $entityManager->persist($message);
        $entityManager->flush();

        $this->addFlash('message', 'Article ajouté avec succès');
        return $this->redirectToRoute('article_show',['id'=>$id]);
    }


         return $this->render('article/show.html.twig', 
         ['subject'=>$subject, 
         'messages' => $messages->findBySubject(
             array($id), 
             array('date_add' => 'DESC')
           ),
           'id'=>$id,
         'messageForm' => $form->createView()
         ]);
     }




    /**
    * @Route("/delete_message/{id}", name="delete_message")
    */
    public function deleteMessage($id)
    {
      $em = $this->getDoctrine()->getManager();
      $messageRepo = $em->getRepository(Message::class);
      $message = $messageRepo->find($id);

     
     
      $em->remove($message);
      $em->flush();

      return $this->redirectToRoute('articles_index');
      
    
    
     

    }






}

templates/article/add_subject.html.twig
{% extends 'base.html.twig' %}

{% block contenu %}
	<style>
		.fa-paper-plane {
			margin-top: -10px;
		}
	</style>
	<link rel="stylesheet" href="{{ asset('css/form.css') }}"/>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">


	<h2>Ajouter un article
	</h2>

	<section class="formulaire">


		{{ form_start(subjectForm) }}
		{{ form_row(subjectForm.title, {'label':'Titre :','attr':{'placeholder':'Titre ...'}}) }}
		{{ form_row(subjectForm.description, {'label':'Description :','attr':{'placeholder':'Description ...'}}) }}
		{{ form_row(subjectForm.ajouter) }}
		<i class="fas fa-paper-plane"></i>
		{{ form_end(subjectForm) }}


	</section>
{% endblock %}

templates/article/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Articles
{% endblock %}

{% block contenu %}
	<link rel="stylesheet" href="{{ asset('css/articles.css') }}"/>

	<div class="more">
		<a href="{{ path('add_subject') }}">
			<i class="fa fa-plus-circle fa-6" aria-hidden="true"></i>
		</a>
	</div>


	<section class="cards">


		{% for subject in subjects %}


			<div class="card with-badge">
				<div class="inner-wrap">
					<h3>
						<a><img src="/uploads/avatars/{{subject.user.avatar}}" alt="">@{{subject.user.pseudo}}</a>
					</h3>
					<a class="title" href="{{ path('article_show',{id : subject.id}) }}">{{subject.title}}</a>
					<p>{{subject.description}}</p>

				</div>
				<div class="likes-bar">
					<p>Nb personnes aime ça</p>
				</div>
				<div class="action-bar">
					<ul>
						<li class="comments">
							<a href="{{ path('article_show',{id : subject.id}) }}">
								<i class="fa fa-comments-o"></i>
								<span class="comments-link">
									Messages</span>
							</a>
						</li>
						<li class="share">
							<a href="#">
								<i class="fa fa-slideshare"></i>
								<span>Partager</span>
							</a>
						</li>
						<li class="like">
							<a href="#">
								<i class="fa fa-heart-o"></i>
								<span>Aimer</span>
							</a>
						</li>
					</ul>
				</div>
			</div>

		{% endfor %}
	</section>
{% endblock %}

templates/article/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Articles
{% endblock %}

{% block contenu %}
	<link rel="stylesheet" href="{{ asset('css/articles.css') }}"/>

	<section class="cards">

		<div class="card with-badge messages">
			<div class="inner-wrap">
				<h3>
					<a href="#"><img src="/uploads/avatars/{{subject.user.avatar}}" alt="">@{{subject.user.pseudo}}</a>
				</h3>
				<h2 class="title">{{subject.title}}</h2>
				<p>{{subject.description}}</p>

			</div>
		</div>

	</section>

	<div class="comments2">
		<div class="comment-wrap">
			<div class="photo">
				<div class="avatar" style="background-image: url('/uploads/avatars/{{app.user.avatar}}')"></div>

			</div>
			<div class="comment-block">
				{{ form_start(messageForm) }}
				{{ form_row(messageForm.text, {'label':'Message :','attr':{'placeholder':'Ajouter un commentaire ...'}}) }}
				{{ form_row(messageForm.ajouter) }}
				{{ form_end(messageForm) }}
			</div>
		</div>

		{% for message in messages %}


			<div class="comment-wrap">
				<div class="photo">
					<div class="avatar" style="background-image: url('/uploads/avatars/{{message.user.avatar}}')"></div>
				</div>
				<div class="comment-block">
					<p class="comment-text">{{ message.text}}</p>
					<div class="bottom-comment">
						<div class="comment-date">{{ message.dateAdd | date('d/m/Y H:i:s') }}</div>
						<ul class="comment-actions">
							{% if app.user.id == message.user.id %}
								<a href="{{ path('delete_message',{id:message.id}) }}" role="button" onclick="return confirm('Êtes-vous sûr de vouloir supprimer ce message ?')">

									<li class="delete">Supprimer</li>
								</a>
							{% endif %}
							<li class="reply">Répondre</li>
						</ul>
					</div>
				</div>
			</div>


		{% endfor %}
	</div>
{% endblock %}